#!/bin/bash

PROVIDER_BINARY="interchain-security-pd"
CONSUMER_BINARY="interchain-security-cd"
PROVIDER_BINARY_PATH=$(which $PROVIDER_BINARY)
CONSUMER_BINARY_PATH=$(which $CONSUMER_BINARY)
HERMES_BINARY_PATH=$(which hermes)
JQ_BINARY_PATH=$(which jq)

CONSUMER_HOME="$HOME/.consumer"
PROVIDER_HOME="$HOME/.provider"
PROVIDER_CHAIN_ID="provider"
CONSUMER_CHAIN_ID="consumer"
CONSUMER_MONIKER="consumer"
PROVIDER_MONIKER="provider"
VALIDATOR="validator"
CONSUMER_USER="consumer"
KEYRING="--keyring-backend test"
TX_FLAGS="--gas-adjustment 100 --gas auto"
NODE_IP="localhost"
PROVIDER_RPC_LADDR="$NODE_IP:26658"
PROVIDER_GRPC_ADDR="$NODE_IP:9091"
CONSUMER_RPC_LADDR="$NODE_IP:26648"
CONSUMER_GRPC_ADDR="$NODE_IP:9081"
PROVIDER_NODE_ADDRESS="tcp://localhost:26658"
TOTAL_COINS=100000000000stake
STAKE_COINS=100000000stake
PROVIDER_DELEGATOR="delegator"